version: '3'
services:
  web:
    build: .
    image: williecadete/lxd-explorer-web:latest
    command: "rackup -o 0.0.0.0 -p 3000 config.ru"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  worker:
    image: williecadete/lxd-explorer-worker:latest
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - INTERVAL=60
      - LXD_HOSTS=https://wcl-lxd-fake-api.herokuapp.com:443

  redis:
    image: redis:alpine
    volumes:
      - redis:/datas

volumes:
  redis:
