version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./test/nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./test/api.json:/usr/share/nginx/html/api/api.json:Z
